name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'type/enhancement'
  patch:
    labels:
      - 'type/bug'
      - 'type/documentation'
      - 'dependencies'
  default: minor

categories:
 - title: 'Features'
   label: 'type/enhancement'
 - title: 'Bug Fixes'
   label: 'type/bug'
 - title: 'Documentation'
   label: 'type/documentation'
 - title: 'Dependencies updates'
   collapse-after: 3
   label: 'dependencies'

exclude-labels:
 - 'skip'

autolabeler:
  - label: 'type/bug'
    title:
      - '/fix.*/'
  - label: 'type/enhancement'
    title:
      - '/feat.*/'
      - '/fix.*/'
      - '/ci.*/'
      - '/chore.*/'
  - label: 'type/documentation'
    files:
      - '*.md'
    title:
      - '/docs.*/'
  - label: 'dependencies'
    title: 
      - '/chore\(update\).*/'

template: |
  # What's Changed

  $CHANGES
